---
ID: "f617cc5e-a04c-4ead-8b13-40cdd7c56a71"
Parent: "61fb365e-0acf-4522-9c2d-4724458237c8"
Template: "61fb365e-0acf-4522-9c2d-4724458237c8"
Path: "/sitecore/templates/Project/na-collection-demo/Events/Contents/Option/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260406T005853Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\naveed.b.ahmad@avanade.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\naveed.b.ahmad@avanade.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2de1638d-3bc0-4af7-a39d-cd670cdee497"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\naveed.b.ahmad@avanade.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260406T005859Z
    - ID: "fdb3911f-17a1-4964-b460-4880a6712b73"
      Hint: Text
      Value: $name
