---
ID: "02010096-ee18-4b2b-8726-f85c7fdcdead"
Parent: "09731ed0-b546-4594-a2f2-7e87a14a4254"
Template: "09731ed0-b546-4594-a2f2-7e87a14a4254"
Path: "/sitecore/templates/Project/na-collection-demo/Headless Site/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260405T210413Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\naveed.b.ahmad@avanade.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\naveed.b.ahmad@avanade.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5d3be668-23f1-4981-b37d-3859a87e6df5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\naveed.b.ahmad@avanade.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260405T210413Z
