---
ID: "53937b8a-f5f6-4a05-b41f-3c38f0e7bf2d"
Parent: "f41c8c81-1a25-4799-8d4b-5ea5b745a8b1"
Template: "f41c8c81-1a25-4799-8d4b-5ea5b745a8b1"
Path: "/sitecore/templates/Project/na-collection-demo/Events/Contents/Option Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{61FB365E-0ACF-4522-9C2D-4724458237C8}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "b603813c-e572-4749-91d3-1b55a988b814"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260406T005844Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\naveed.b.ahmad@avanade.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\naveed.b.ahmad@avanade.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "33f4fcec-86bd-4e7d-995e-fd8261abe772"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\naveed.b.ahmad@avanade.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260406T010147Z
